version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: my-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Abc12344321
      MONGO_INITDB_DATABASE: mydb
    volumes:
      - ./mongodb-data:/data/db
volumes:
  mongodb-data:
