
@url_dev= http://localhost:3006/v1/api
### signUp
POST {{url_dev}}/shop/signup
Content-Type: application/json
x-api-key: aedacc4eb033baaf3612a9ccb9593afd25e8446cbb4c876d2606a9609b8b06735c60a57bbb394def522e9bc8b44b3f948bf5bce93acea8d89b068b94d8089c4c

{
    "name":"Shop quan ao",
    "email":"ShopQuanAo05@gmail.com",
    "password":"abc@123"
}